#!/bin/bash

# Script to fix the IJitsiConference interface in reducer.ts with proper function signatures

file="features/base/conference/reducer.ts"

echo "Fixing IJitsiConference interface in $file..."

sed -i '' 's/    addCommandListener: Function;/    addCommandListener: (command: string, handler: Function) =\u003e void;/g' "$file"
sed -i '' 's/    addLobbyMessageListener: Function;/    addLobbyMessageListener: (handler: Function) =\u003e void;/g' "$file"
sed -i '' 's/    addTrack: Function;/    addTrack: (track: any) =\u003e Promise\u003cvoid\u003e;/g' "$file"
sed -i '' 's/    authenticateAndUpgradeRole: Function;/    authenticateAndUpgradeRole: (options: any) =\u003e Promise\u003cany\u003e;/g' "$file"
sed -i '' 's/    avModerationApprove: Function;/    avModerationApprove: (mediaType: string) =\u003e void;/g' "$file"
sed -i '' 's/    createVideoSIPGWSession: Function;/    createVideoSIPGWSession: (address: string, displayName: string) =\u003e void;/g' "$file"
sed -i '' 's/    dial: Function;/    dial: (number: string) =\u003e void;/g' "$file"
sed -i '' 's/    disableAVModeration: Function;/    disableAVModeration: (mediaType: string) =\u003e void;/g' "$file"
sed -i '' 's/    disableLobby: Function;/    disableLobby: () =\u003e void;/g' "$file"
sed -i '' 's/    enableAVModeration: Function;/    enableAVModeration: (mediaType: string) =\u003e void;/g' "$file"
sed -i '' 's/    enableLobby: Function;/    enableLobby: () =\u003e void;/g' "$file"
sed -i '' 's/    end: Function;/    end: () =\u003e Promise\u003cvoid\u003e;/g' "$file"
sed -i '' 's/    getBreakoutRooms: Function;/    getBreakoutRooms: () =\u003e any;/g' "$file"
sed -i '' 's/    getConnection: Function;/    getConnection: () =\u003e any;/g' "$file"
sed -i '' 's/    getFileSharing: Function;/    getFileSharing: () =\u003e any;/g' "$file"
sed -i '' 's/    getLocalParticipantProperty: Function;/    getLocalParticipantProperty: (key: string) =\u003e any;/g' "$file"
sed -i '' 's/    getLocalTracks: Function;/    getLocalTracks: () =\u003e any[];/g' "$file"
sed -i '' 's/    getMeetingUniqueId: Function;/    getMeetingUniqueId: () =\u003e string;/g' "$file"
sed -i '' 's/    getMetadataHandler: Function;/    getMetadataHandler: () =\u003e any;/g' "$file"
sed -i '' 's/    getName: Function;/    getName: () =\u003e string;/g' "$file"
sed -i '' 's/    getParticipantById: Function;/    getParticipantById: (id: string) =\u003e any;/g' "$file"
sed -i '' 's/    getParticipants: Function;/    getParticipants: () =\u003e any[];/g' "$file"
sed -i '' 's/    getPolls: Function;/    getPolls: () =\u003e any;/g' "$file"
sed -i '' 's/    getRole: Function;/    getRole: () =\u003e string;/g' "$file"
sed -i '' 's/    getShortTermCredentials: Function;/    getShortTermCredentials: () =\u003e any;/g' "$file"
sed -i '' 's/    getSsrcByTrack: Function;/    getSsrcByTrack: (track: any) =\u003e number | null;/g' "$file"
sed -i '' 's/    getTranscriptionStatus: Function;/    getTranscriptionStatus: () =\u003e string;/g' "$file"
sed -i '' 's/    grantOwner: Function;/    grantOwner: (participantId: string) =\u003e void;/g' "$file"
sed -i '' 's/    isAVModerationSupported: Function;/    isAVModerationSupported: (mediaType: string) =\u003e boolean;/g' "$file"
sed -i '' 's/    isE2EEEnabled: Function;/    isE2EEEnabled: () =\u003e boolean;/g' "$file"
sed -i '' 's/    isE2EESupported: Function;/    isE2EESupported: () =\u003e boolean;/g' "$file"
sed -i '' 's/    isEndConferenceSupported: Function;/    isEndConferenceSupported: () =\u003e boolean;/g' "$file"
sed -i '' 's/    isLobbySupported: Function;/    isLobbySupported: () =\u003e boolean;/g' "$file"
sed -i '' 's/    isP2PActive: Function;/    isP2PActive: () =\u003e boolean;/g' "$file"
sed -i '' 's/    isSIPCallingSupported: Function;/    isSIPCallingSupported: () =\u003e boolean;/g' "$file"
sed -i '' 's/    join: Function;/    join: (password?: string) =\u003e Promise\u003cvoid\u003e;/g' "$file"
sed -i '' 's/    joinLobby: Function;/    joinLobby: (displayName?: string, email?: string) =\u003e void;/g' "$file"
sed -i '' 's/    leave: Function;/    leave: () =\u003e Promise\u003cvoid\u003e;/g' "$file"
sed -i '' 's/    lobbyApproveAccess: Function;/    lobbyApproveAccess: (userId: string) =\u003e void;/g' "$file"
sed -i '' 's/    lobbyDenyAccess: Function;/    lobbyDenyAccess: (userId: string) =\u003e void;/g' "$file"
sed -i '' 's/    lock: Function;/    lock: (password: string) =\u003e Promise\u003cvoid\u003e;/g' "$file"
sed -i '' 's/    markParticipantVerified: Function;/    markParticipantVerified: (participantId: string, verified: boolean) =\u003e void;/g' "$file"
sed -i '' 's/    myLobbyUserId: Function;/    myLobbyUserId: () =\u003e string;/g' "$file"
sed -i '' 's/    myUserId: Function;/    myUserId: () =\u003e string;/g' "$file"
sed -i '' 's/    off: Function;/    off: (event: string, handler: Function) =\u003e void;/g' "$file"
sed -i '' 's/    on: Function;/    on: (event: string, handler: Function) =\u003e void;/g' "$file"
sed -i '' 's/    removeTrack: Function;/    removeTrack: (track: any) =\u003e Promise\u003cvoid\u003e;/g' "$file"
sed -i '' 's/    replaceTrack: Function;/    replaceTrack: (oldTrack: any | null, newTrack: any | null) =\u003e Promise\u003cvoid\u003e;/g' "$file"
sed -i '' 's/    sendApplicationLog: Function;/    sendApplicationLog: (log: string) =\u003e void;/g' "$file"
sed -i '' 's/    sendCommand: Function;/    sendCommand: (name: string, attributes: any) =\u003e void;/g' "$file"
sed -i '' 's/    sendCommandOnce: Function;/    sendCommandOnce: (name: string, attributes: any) =\u003e void;/g' "$file"
sed -i '' 's/    sendEndpointMessage: Function;/    sendEndpointMessage: (to: string, payload: any) =\u003e void;/g' "$file"
sed -i '' 's/    sendFeedback: Function;/    sendFeedback: (score: number, message: string) =\u003e Promise\u003cvoid\u003e;/g' "$file"
sed -i '' 's/    sendLobbyMessage: Function;/    sendLobbyMessage: (message: string) =\u003e void;/g' "$file"
sed -i '' 's/    sendMessage: Function;/    sendMessage: (message: string, to?: string) =\u003e void;/g' "$file"
sed -i '' 's/    sendPrivateTextMessage: Function;/    sendPrivateTextMessage: (id: string, message: string) =\u003e void;/g' "$file"
sed -i '' 's/    sendReaction: Function;/    sendReaction: (reaction: string) =\u003e void;/g' "$file"
sed -i '' 's/    sendTextMessage: Function;/    sendTextMessage: (message: string, elementName?: string) =\u003e void;/g' "$file"
sed -i '' 's/    sendTones: Function;/    sendTones: (tones: string, duration: number, pause: number) =\u003e void;/g' "$file"
sed -i '' 's/    setDesktopSharingFrameRate: Function;/    setDesktopSharingFrameRate: (frameRate: number) =\u003e void;/g' "$file"
sed -i '' 's/    setDisplayName: Function;/    setDisplayName: (displayName: string) =\u003e void;/g' "$file"
sed -i '' 's/    setLocalParticipantProperty: Function;/    setLocalParticipantProperty: (name: string, value: any) =\u003e void;/g' "$file"
sed -i '' 's/    setMediaEncryptionKey: Function;/    setMediaEncryptionKey: (keyInfo: any) =\u003e void;/g' "$file"
sed -i '' 's/    setReceiverConstraints: Function;/    setReceiverConstraints: (constraints: any) =\u003e void;/g' "$file"
sed -i '' 's/    setStartMutedPolicy: Function;/    setStartMutedPolicy: (policy: any) =\u003e void;/g' "$file"
sed -i '' 's/    setTranscriptionLanguage: Function;/    setTranscriptionLanguage: (language: string) =\u003e void;/g' "$file"
sed -i '' 's/    startRecording: Function;/    startRecording: (options: any) =\u003e Promise\u003cany\u003e;/g' "$file"
sed -i '' 's/    startVerification: Function;/    startVerification: (id: string) =\u003e void;/g' "$file"
sed -i '' 's/    stopRecording: Function;/    stopRecording: (sessionID: string) =\u003e void;/g' "$file"
sed -i '' 's/    toggleE2EE: Function;/    toggleE2EE: (enabled: boolean) =\u003e void;/g' "$file"

echo "IJitsiConference interface fixed!"
